spring:
  datasource:
    username: freedy
    password: Kz99596589
    url: jdbc:mysql://freedyamazing.rwlb.rds.aliyuncs.com:3306/mall_oms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000


freedymall:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10


